name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish MinMaNet.API/MinMaNet.API.csproj -c Release -o release --nologo

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MinmaNet_Published
        path: /home/runner/work/MinmaNet/MinmaNet/release/
    - name: Create folder
        run: |
          mkdir -p /home/runner/work/MinmaNet/MinmaNet/release/abc && cp -R dist /home/runner/work/MinmaNet/MinmaNet/release/abc
    - name: Commit release to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: release
        FOLDER: release

    # Download Artifact #1 and verify the correctness of the content
    - name: 'Download artifact #1'
      uses: actions/download-artifact@v1
      with:
        name: 'MinmaNet_Published'
        path: newfolder

    - name: Display structure of downloaded files
      run: ls -R